= Code size reduction meeting minutes

== C.LH, C.LB (signed versions)

Tariq presented the benchmark results (all generated by Ibrahim), including C.LB and C.LH as suggested by John Hauser.

Looking at the results it's clear that the compiler has a choice about whether to use the signed or unsigned versions, in some cases at least. 
The proportion of signed to unsigned is quite different between GCC and LLVM.

We believe that GCC doesn't consider whether there is a 16-bit encoding available when compiling the code, that is left to the assembler.
LLVM does, and and so does IAR we believe.

It would be helpful to have compiler input to help choose which versions are the most useful.

== BEQI, BNEI

It's possible that once BEQI is implemented BNEI won't be as necessary - which brings us to a more general point - it's very hard to know how useful instructions will really be until 
we have a good compiler implementation.

Evandro points out that it's better to have both as symmetry is good for the compiler.

Torbjorn said we should reserve the cases where the comparison either has x0 or the immediate is zero as these are covered by BEQ x0 or C.BEQ etc.

== B-extension

It's possible that compiling with B enabled will reduce the usefulness of some of the proposals. We should try this with the lastest LLVM.

== Others

Should benchmark against -msave-restore which includes mv instructions. 

== MULIADD/ADDIADD

These are unpopular with John Hauser and Andrew Waterman. ADDIADD doesn't have great value and MULIADD's value is more than compensated for with MULI - which is more regular to implement.

_I'll remove ADDIADD and MULIADD_

Plus DECBNEZ is proving to be tricky, and maybe BNEI/BEQI reduces its value. I think I'll *postpone* it, unless someone comes forwards with a compelling reason to keep it.

== Next steps

Trim awkward instructions. If the encodings fit, then keep them and see if anyone can find uses for them (e.g. C.NEG/C.NOT which are pretty useless at the moment but they are cheap and the encodings fit well).

Don't trim well behaved instructions until more code has been analysed.




